data <- read.csv("result.csv")
frequency <- table(data$stars_x)
barplot(frequency, col = 'blue', xlab = 'rating', ylab = 'Frequency')
frequencey <- table(data$GoodForKids)
barplot(frequencey)
par(mfrow = c(2,2))
boxplot(stars_x~WiFi,data=data,col = 'red', xlab= 'WiFi', ylab = 'rating')
boxplot(stars_x~HasTV,data=data,col = 'red',xlab= 'HasTV', ylab = 'rating')
boxplot(stars_x~GoodForKids,data=data,col = 'red',xlab= 'GoodForKids', ylab = 'rating')
boxplot(stars_x~Alcohol,data=data,col = 'red',xlab= 'Alcohol', ylab = 'rating')
par(mfrow = c(1,1))
par(mfrow = c(2,2))
frequencey <- table(data$GoodForKids)
barplot(frequencey, col = rainbow(5), xlab = 'Good For Kids', ylab = 'Frequency')
frequencey1 <- table(data$HasTV)
barplot(frequencey1, col = rainbow(5), xlab = 'Has TV', ylab = 'Frequency')
frequencey2 <- table(data$Alcohol)
barplot(frequencey2, col = rainbow(5), xlab = 'Alcohol', ylab = 'Frequency')
frequencey3 <- table(data$WiFi)
barplot(frequencey3, col = rainbow(5), xlab = 'WiFi', ylab = 'Frequency')
