data <- read.csv("answer.csv")
test <- lm(stars_x~RestaurantsTakeOut,data=data)
summary(test)
test1 <- lm(stars_x~HasTV,data=data)
summary(test1)
test2 <- lm(stars_x~NoiseLevel,data=data)
summary(test2)
test3 <- lm(stars_x~Alcohol,data=data)
summary(test3)
test4 <- lm(stars_x~RestaurantsGoodForGroups,data=data)
summary(test4)
test4 <- lm(stars_x~BusinessAcceptsCreditCards,data=data)
summary(test4)
test5 <- lm(stars_x~Caters,data=data)
summary(test5)
test6 <- lm(stars_x~RestaurantsPriceRange2,data=data)
summary(test6)
test7 <- lm(stars_x~RestaurantsAttire,data=data)
summary(test7)
test8 <- lm(stars_x~BikeParking,data=data)
summary(test8)
test9 <- lm(stars_x~GoodForKids,data=data)
summary(test9)
test10 <- lm(stars_x~RestaurantsReservations,data=data)
summary(test10)
test11 <- lm(stars_x~BusinessAcceptsBitcoin,data=data)
summary(test11)
test12 <- lm(stars_x~WiFi,data=data)
summary(test12)
test13 <- lm(stars_x~HappyHour,data=data)
summary(test13)
test14 <- lm(stars_x~CoatCheck,data=data)
summary(test14)
test15 <- lm(stars_x~RestaurantsDelivery,data=data)
summary(test15)
test16 <- lm(stars_x~OutdoorSeating,data=data)
summary(test16)
test17 <- lm(stars_x~WheelchairAccessible,data=data)
summary(test17)
test18 <- lm(stars_x~RestaurantsTableService,data=data)
summary(test18)
test19 <- lm(stars_x~ByAppointmentOnly,data=data)
summary(test19)
test20 <- lm(stars_x~DogsAllowed,data=data)
summary(test20)
test21 <- lm(stars_x~touristy,data=data)
summary(test21)
test22 <- lm(stars_x~hipster,data=data)
summary(test22)
test23 <- lm(stars_x~romantic,data=data)
summary(test23)
test24 <- lm(stars_x~divey,data=data)
summary(test24)
test25 <- lm(stars_x~intimate,data=data)
summary(test25)
test26 <- lm(stars_x~trendy,data=data)
summary(test26)
test27 <- lm(stars_x~upscale,data=data)
summary(test27)
test28 <- lm(stars_x~classy,data=data)
summary(test28)
test29 <- lm(stars_x~casual,data=data)
summary(test29)
test30 <- lm(stars_x~breakfast,data=data)
summary(test30)
test31 <- lm(stars_x~brunch,data=data)
summary(test31)
test32 <- lm(stars_x~lunch,data=data)
summary(test32)
test33 <- lm(stars_x~latenight,data=data)
summary(test33)
test34 <- lm(stars_x~dessert,data=data)
summary(test34)
test35 <- lm(stars_x~dj,data=data)
summary(test35)
test36 <- lm(stars_x~live,data=data)
summary(test36)
test37 <- lm(stars_x~jukebox,data=data)
summary(test37)
test38 <- lm(stars_x~video,data=data)
summary(test38)
test39 <- lm(stars_x~background_music,data=data)
summary(test39)
test40 <- lm(stars_x~karaoke,data=data)
summary(test40)
test41 <- lm(stars_x~no_music,data=data)
summary(test41)
model1 <- lm(stars_x~BikeParking+HasTV+Alcohol+NoiseLevel+RestaurantsTableService+touristy+romantic+classy+casual+lunch,data=data)
summary(model1)
model2 <- lm(stars_x~BikeParking+HasTV+Alcohol+NoiseLevel+RestaurantsTableService+romantic+classy+casual+lunch,data=data)
summary(model2)
anova(model2,model1)
model3 <- lm(stars_x~BikeParking+HasTV+Alcohol+NoiseLevel+RestaurantsTableService+classy+casual+lunch,data=data)
anova(model3,model2)
model4 <-lm(stars_x~BikeParking+HasTV+Alcohol+NoiseLevel+RestaurantsTableService+romantic+casual+lunch,data=data)
anova(model4,model2)
model5 <-lm(stars_x~BikeParking+HasTV+Alcohol+NoiseLevel+RestaurantsTableService+romantic+classy+lunch,data=data)
anova(model5,model2)
model6 <-lm(stars_x~BikeParking+HasTV+Alcohol+NoiseLevel+RestaurantsTableService+romantic+classy,data=data)
anova(model6,model5)
model7 <-lm(stars_x~BikeParking+HasTV+Alcohol+NoiseLevel+romantic+classy,data=data)
anova(model7,model6)
model8 <-lm(stars_x~BikeParking+HasTV+Alcohol+RestaurantsTableService+romantic+classy,data=data)
anova(model8,model6)
model9 <-lm(stars_x~BikeParking+HasTV+RestaurantsTableService+romantic+classy,data=data)
anova(model9,model8)
model10 <- lm(stars_x~BikeParking+RestaurantsTableService+romantic+classy,data=data)
anova(model10,model9)
model11 <- lm(stars_x~HasTV+RestaurantsTableService+romantic+classy,data=data)
anova(model11,model9)
model12 <- lm(stars_x~HasTV+RestaurantsTableService+romantic+classy+RestaurantsAttire,data=data)
anova(model11,model12)
summary(model11)


