data <- read.csv("result.csv")
model1 <- glm(stars_x~RestaurantsTakeOut,data=data) 
summary(model1)
model2 <- glm(stars_x~HasTV,data=data)
summary(model2)
model3 <- glm(stars_x~NoiseLevel,data=data)
summary(model3)
model4 <- glm(stars_x~Alcohol,data=data)
summary(model4)
model5 <- glm(stars_x~RestaurantsGoodForGroups,data=data)
summary(model5)
model6 <- glm(stars_x~BusinessAcceptsCreditCards,data=data)
summary(model6)
model7 <- glm(stars_x~Caters,data=data)
summary(model7)
model8 <- glm(stars_x~RestaurantsAttire,data=data)
summary(model8)
model9 <- glm(stars_x~BikeParking,data=data)
summary(model9)
model10 <- glm(stars_x~GoodForKids,data=data)
summary(model10)
model11 <- glm(stars_x~RestaurantsReservations,data=data)
summary(model11)
model12 <- glm(stars_x~BusinessAcceptsBitcoin,data=data)
summary(model12)
model13 <- glm(stars_x~WiFi,data=data)
summary(model13)
model14 <- glm(stars_x~RestaurantsDelivery,data=data)
summary(model14)
model15 <- glm(stars_x~GoodForDancing,data=data)
summary(model15)
model16 <- glm(stars_x~HappyHour,data=data)
summary(model16)
model17 <- glm(stars_x~CoatCheck,data=data)
summary(model17)
model18 <- glm(stars_x~OutdoorSeating,data=data)
summary(model18)
model19 <- glm(stars_x~DriveThru,data=data)
summary(model19)
model20 <- glm(stars_x~WheelchairAccessible,data=data)
summary(model20)
model21 <- glm(stars_x~RestaurantsTableService,data=data)
summary(model21)
model22 <- glm(stars_x~BYOB,data=data)
summary(model22)
model23 <- glm(stars_x~Corkage,data=data)
summary(model23)
model24 <- glm(stars_x~ByAppointmentOnly,data=data)
summary(model24)
model25 <- glm(stars_x~DogsAllowed,data=data)
summary(model25)
model26 <- glm(stars_x~Smoking,data=data)
summary(model26)
data2 <- read.csv("goodformeal.csv")
model27 <- glm(stars_x~breakfast,data=data2)
summary(model27)
model28 <- glm(stars_x~brunch,data=data2)
summary(model28)
model29 <- glm(stars_x~lunch,data=data2)
summary(model29)
model30 <- glm(stars_x~dinner,data=data2)
summary(model30)
model31 <- glm(stars_x~latenight,data=data2)
summary(model31)
model32 <- glm(stars_x~dessert,data=data2)
summary(model32)
data3 <- read.csv("ambience.csv")
model33 <- glm(stars_x~touristy,data=data3)
summary(model33)
model34 <- glm(stars_x~hipster,data=data3)
summary(model34)
model35 <- glm(stars_x~romantic,data=data3)
summary(model35)
model36 <- glm(stars_x~divey,data=data3)
summary(model36)
model37 <- glm(stars_x~intimate,data=data3)
summary(model37)
model38 <- glm(stars_x~trendy,data=data3)
summary(model38)
model39 <- glm(stars_x~upscale,data=data3)
summary(model39)
model40 <- glm(stars_x~classy,data=data3)
summary(model40)
model41 <- glm(stars_x~casual,data=data3)
summary(model41)
data4 <- read.csv("businessparking.csv")
model42 <- glm(stars_x~garage,data=data4)
summary(model42)
model43 <- glm(stars_x~street,data=data4)
summary(model43)
model44 <- glm(stars_x~validated,data=data4)
summary(model44)
model45 <- glm(stars_x~lot,data=data4)
summary(model45)
model46 <- glm(stars_x~valet,data=data4)
summary(model46)

data5 <- read.csv("music.csv")
model47 <- glm(stars_x~dj,data=data5)
summary(model47)
model48 <- glm(stars_x~live,data=data5)
summary(model48)
model49 <- glm(stars_x~jukebox,data=data5)
summary(model49)
model50 <- glm(stars_x~video,data=data5)
summary(model50)
model51 <- glm(stars_x~background_music,data=data5)
summary(model51)
model52 <- glm(stars_x~karaoke,data=data5)
summary(model52)

data6 <- read.csv("bestnights.csv")
model53 <- glm(stars_x~monday,data=data6)
summary(model53)
model54 <- glm(stars_x~tuesday,data=data6)
summary(model54)
model55 <- glm(stars_x~wednesday,data=data6)
summary(model55)
model56 <- glm(stars_x~thursday,data=data6)
summary(model56)
model57 <- glm(stars_x~friday,data=data6)
summary(model57)
model58 <- glm(stars_x~saturday,data=data6)
summary(model58)
model59 <- glm(stars_x~sunday,data=data6)
summary(model59)
